[package]
name = "source-cache"
version.workspace = true
authors.workspace = true
description = "Query the cache of raw text"
repository = "https://github.com/oovm/diagnostic-rs/tree/dev/projects/source-cache"
documentation = "https://docs.rs/source-cache"
readme = "readme.md"
license.workspace = true
edition.workspace = true

[dependencies]
url = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde", "url/serde"]

[package.metadata.docs.rs]
all-features = true
