[package]
name = "source-cache"
version.workspace = true
authors.workspace = true
description = "Deprecated transitional cache. Use the source crate and diagnostic::terminal::SourceCache instead"
repository = "https://github.com/oovm/diagnostic-rs/tree/dev/projects/source-cache"
documentation = "https://docs.rs/source-cache"
readme = "readme.md"
license.workspace = true
edition.workspace = true

[dependencies]
url = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = ["std"]
std = ["dep:url"]
serde = ["dep:serde", "url?/serde"]

[package.metadata.docs.rs]
all-features = true
