[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/validation",
    "projects/source-cache",
    "projects/diagnostic",
]
exclude = [
    "projects/.DS_Store",
    "projects/diagnostic-lsp",
    "projects/diagnostic-quick",
    "projects/diagnostic-svg",
    "projects/syntax-error",
]

[profile.release]
lto = true
panic = "abort"
