[package]
name = "diagnostic-macro"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
description = "Procedural macro helpers for structured diagnostics"
homepage = "https://github.com/oovm/diagnostic-rs"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/diagnostic-macro"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
diagnostic = { workspace = true }

[dev-dependencies]
diagnostic = { workspace = true }

[[example]]
name = "structured"
path = "examples/structured.rs"
required-features = []
