[package]
name = "validation"
version.workspace = true
readme = "readme.md"
license = "Apache-2.0"
authors.workspace = true
description = "Validator types, returns multiple tolerable errors at once"
homepage = "https://github.com/oovm/diagnostic-rs"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/validation"
exclude = ["tests/**"]
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
unindent = { workspace = true }

[features]
default = []
nightly = []
