[package]
name = "diagnostic-lsp"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
description = "UTF-16 position mapping and structured diagnostic conversion for LSP clients"
homepage = "https://github.com/oovm/diagnostic-rs"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/diagnostic-lsp"
edition.workspace = true

[dependencies]
lsp-types = { workspace = true }
url = { workspace = true }
diagnostic = { workspace = true, features = ["serde"] }
source-cache = { workspace = true }

[dev-dependencies]
diagnostic = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }
