[package]
name = "diagnostic-quick"
version.workspace = true
authors.workspace = true
description = "Quick error type for diagnostic"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/diagnostic-quick"
readme = "readme.md"
license.workspace = true
edition.workspace = true

[dependencies]
diagnostic = { workspace = true }
lsp-types = { workspace = true, optional = true }
ropey = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
ucd-trie = { workspace = true, optional = true }
sled = { workspace = true, optional = true }
serde = { workspace = true }
toml = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde-binary = { workspace = true, optional = true }
url = { workspace = true, optional = true, features = ["serde"] }
num = { workspace = true, optional = true, features = ["serde"] }
email_address = { workspace = true, optional = true, features = ["serde"] }
semver = { workspace = true, optional = true, features = ["serde"] }
mime = { workspace = true, optional = true, features = [] }
peginator = { workspace = true, optional = true }
tl = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
globset = { workspace = true, optional = true }
fs-tools = { workspace = true, optional = true }
font-kit = { workspace = true, optional = true }
pathfinder = { workspace = true, optional = true }
image = { workspace = true, optional = true }
imageproc = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winreg = { workspace = true, optional = true }

[features]
default = []
walk = ["dep:fs-tools"]
async-walk = ["dep:fs-tools", "fs-tools/async"]

[package.metadata.docs.rs]
all-features = true
