[package]
name = "console"
version.workspace = true
authors.workspace = true
description = "Structured console event facade, sinks, spans, and generic terminal styling"
repository = "https://github.com/oovm/diagnostic-rs/tree/dev/projects/console"
readme = "readme.md"
license.workspace = true
edition.workspace = true

[dependencies]
logger = { workspace = true }
terminal = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }

[features]
default = ["std"]
std = []
concolor = []

[package.metadata.docs.rs]
all-features = true
