[package]
name = "diagnostic-svg"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
description = "Structured diagnostic SVG preview rendering"
homepage = "https://github.com/oovm/diagnostic-rs"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/diagnostic-svg"
edition.workspace = true

[dependencies]
diagnostic = { workspace = true }
