[package]
name = "diagnostic-svg"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
description = "Conversions between codespan types and Language Server Protocol types"
homepage = "https://github.com/brendanzab/codespan"
repository = "https://github.com/brendanzab/codespan"
documentation = "https://docs.rs/codespan-lsp"
edition.workspace = true

[dependencies]
lsp-types = { workspace = true }
url = { workspace = true }
diagnostic = { workspace = true }
