[package]
name = "syntax-error"
version.workspace = true
readme = "readme.md"
license = "Apache-2.0"
authors = ["Aster <192607617@qq.com>", "Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "Beautiful diagnostic reporting for text-based programming languages"
homepage = "https://github.com/oovm/diagnostic-rs"
repository = "https://github.com/oovm/diagnostic-rs"
documentation = "https://docs.rs/diagnostic"
exclude = ["tests/**"]
edition.workspace = true

[dependencies]
diagnostic = { workspace = true }
dashu = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
num = { workspace = true, optional = true }
url = { workspace = true, optional = true }
pex = { workspace = true, optional = true }
regex = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde", "num?/serde"]
