[package]
name = "diagnostic"
version.workspace = true
authors.workspace = true
description = "Structured diagnostic data model with optional terminal rendering"
repository = "https://github.com/oovm/diagnostic-rs/tree/dev/projects/diagnostic"
documentation = "https://docs.rs/diagnostic"
readme = "readme.md"
license.workspace = true
edition.workspace = true
exclude = ["package.json", "tests/**"]

[dependencies]
serde = { workspace = true, optional = true }
unicode-width = { workspace = true, optional = true }
source-cache = { workspace = true, optional = true }
terminal = { workspace = true, optional = true }
logger = { workspace = true, optional = true }
console = { workspace = true, optional = true }

[dev-dependencies]
serial_test = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["std"]
std = []
serde = ["dep:serde"]
logger = ["dep:logger", "std"]
console = ["dep:console", "logger"]
terminal = ["console", "dep:terminal", "dep:source-cache", "dep:unicode-width"]
concolor = ["console/concolor"]

[package.metadata.docs.rs]
all-features = true
